✨ Show/hide data
LouisaStrunk02/HTML-Table pull request #2
Opened 2022-09-13 13:40 UTC by LouisaStrunk02

Changes:

1. add id`s
2. add function "visibility"

2022-09-14 06:34 UTC, DevBastiS requested changes

2022-09-14 06:34 UTC, DevBastiS commented on table.html
> +        <th id="name" onclick="visibility(this.id)" class="table-head__cell">Name</th>
ids have to be unique.

2022-09-14 06:56 UTC, stefanluth commented on table.js
> +function visibility(columnId) {
2 spaces indents

2022-09-14 07:56 UTC, stefanluth commented on table.js
>  function visibility(columnId) {
Function names should include a verb to show what the function does :) E.g.

`changeVisibility` or `toggleVisibility`

2022-09-14 08:00 UTC, stefanluth requested changes

2022-09-14 08:00 UTC, stefanluth commented on table.html
> +        <td name="name" class="table-body__cell">Hans</td>
According to w3schools, the `td`-tag does not support the `name`-attribute; It only supports [these](https://www.w3schools.com/tags/tag_td.asp) and the `[global attributes](https://www.w3schools.com/tags/ref_standardattributes.asp)`.

2022-09-14 08:01 UTC, stefanluth commented on table.html
> +        <td name="name" class="table-body__cell">Hans</td>
Depending on what the intended purpose of the "name"-tag was, it could be enough to place it in the class name instead.

2022-09-15 06:07 UTC, DevBastiS approved these changes
What @stefanluth said

2022-09-16 08:16 UTC, stefanluth approved these changes
lgtm :)

2022-09-20 05:53 UTC, merged